# Algebra liniowa

## Wektory

### Czym jest wektor?

Wektor to obiekt matematyczny, który ma zarówno **wielkość** (długość), jak i **kierunek**. Można go przedstawić graficznie jako strzałkę.

**Przykłady z życia codziennego:**

* **Prędkość:**  Kiedy mówisz, że samochód porusza się z prędkością 60 km/h na północ, opisujesz wektor.  60 km/h to wielkość (długość strzałki), a północ to kierunek.
* **Siła:** Kiedy pchasz szafę, używasz siły o określonej wielkości i kierunku. To również jest wektor!
* **Przemieszczenie:**  Kiedy idziesz 100 metrów na wschód, twoje przemieszczenie jest wektorem o wielkości 100 metrów i kierunku wschodnim.

### Jak zapisujemy wektory?

Wektory możemy zapisywać na kilka sposobów:

* **Współrzędne:** W układzie współrzędnych (np. na płaszczyźnie XY) wektor można zapisać jako parę liczb (x, y), gdzie x to współrzędna pozioma, a y to współrzędna pionowa. Np. wektor (3, 4)  zaczyna się w punkcie (0, 0) i kończy w punkcie (3, 4).
* **Symbol strzałki:**  Wektor można oznaczyć literą ze strzałką nad nią, np.  $\vec{v}$
* **Macierz kolumnowa:** W algebrze liniowej często zapisujemy wektory jako macierze kolumnowe, np.  
  $\vec{v} = \begin{bmatrix} 3 \\ 4 \end{bmatrix}$

### Działania na wektorach

Na wektorach możemy wykonywać różne operacje:

* **Dodawanie:**  Dodajemy wektory, dodając do siebie ich odpowiadające współrzędne. Np. (1, 2) + (3, 1) = (4, 3). Graficznie dodawanie wektorów polega na "doklejeniu"  końca jednego wektora do początku drugiego.
* **Odejmowanie:** Odejmowanie wektorów działa analogicznie do dodawania, tylko odejmujemy odpowiadające współrzędne. Np. (4, 3) - (1, 2) = (3, 1).
* **Mnożenie przez skalar:** Mnożymy wektor przez liczbę (skalar), mnożąc każdą współrzędną wektora przez ten skalar. Np. 2 * (1, 2) = (2, 4).  Graficznie mnożenie przez skalar zmienia długość wektora.

In [1]:
import numpy as np

# Tworzenie wektorów
v1 = np.array([1, 2])
v2 = np.array([3, 1])

# Dodawanie wektorów
v3 = v1 + v2
print(f"Suma wektorów: {v3}")

# Odejmowanie wektorów
v4 = v2 - v1
print(f"Różnica wektorów: {v4}")

# Mnożenie wektora przez skalar
v5 = 2 * v1
print(f"Wektor v1 pomnożony przez 2: {v5}")


Suma wektorów: [4 3]
Różnica wektorów: [ 2 -1]
Wektor v1 pomnożony przez 2: [2 4]


In [ ]:
### Zadania w Python i NumPy

# 1. Utwórz wektor `a` o współrzędnych (2, 5) i wektor `b` o współrzędnych (-1, 3).
# 2. Dodaj wektory `a` i `b`, wynik zapisz w zmiennej `c`.
# 3. Odejmij wektor `b` od wektora `a`, wynik zapisz w zmiennej `d`.
# 4. Pomnóż wektor `a` przez skalar 3, wynik zapisz w zmiennej `e`.
# 5. **(Zadanie trudniejsze)** Napisz funkcję, która oblicza długość wektora (normę euklidesową).  Norma euklidesowa wektora (x, y) to  $\sqrt{x^2 + y^2}$.

In [ ]:
### Odpowiedzi do zadań

import numpy as np

# 1. Tworzenie wektorów
a = np.array([2, 5])
b = np.array([-1, 3])

# 2. Dodawanie wektorów
c = a + b
print(f"Suma wektorów a i b: {c}")

# 3. Odejmowanie wektorów
d = a - b
print(f"Różnica wektorów a i b: {d}")

# 4. Mnożenie wektora przez skalar
e = 3 * a
print(f"Wektor a pomnożony przez 3: {e}")


# 5. Funkcja obliczająca długość wektora
def dlugosc_wektora(wektor):
    """Oblicza długość wektora (normę euklidesową)."""
    return np.sqrt(np.sum(wektor**2))


print(f"Długość wektora a: {dlugosc_wektora(a)}")

### Notatka do powtórki

* **Wektor:** Obiekt matematyczny mający wielkość i kierunek.
* **Zapisywanie wektorów:** Współrzędne (x, y), symbol strzałki ($\vec{v}$), macierz kolumnowa.
* **Działania na wektorach:** Dodawanie, odejmowanie, mnożenie przez skalar.
* **NumPy:** Biblioteka Pythona do obliczeń numerycznych, ułatwiająca pracę z wektorami.

### Podsumowanie

Wektory to podstawowe narzędzie w algebrze liniowej i wielu dziedzinach nauki i techniki. Umiejętność wykonywania operacji na wektorach jest niezbędna do dalszej nauki.

## Norma wektora

Norma wektora to funkcja, która przypisuje wektorowi nieujemną liczbę rzeczywistą. Intuicyjnie, norma wektora określa jego "długość" lub "wielkość".

### Rodzaje norm

Istnieje wiele różnych norm, ale niektóre z najpopularniejszych to:

* **Norma euklidesowa (norma L2):**  Jest to najbardziej intuicyjna norma, która odpowiada "zwykłej" długości wektora. Obliczamy ją, pierwiastkując sumę kwadratów współrzędnych wektora. Dla wektora  $\vec{v} = \begin{bmatrix} x \\ y \end{bmatrix}$ norma euklidesowa wynosi:

  $||\vec{v}||_2 = \sqrt{x^2 + y^2}$

* **Norma Manhattan (norma L1):**  Tę normę oblicza się, sumując wartości bezwzględne współrzędnych wektora. Dla wektora  $\vec{v} = \begin{bmatrix} x \\ y \end{bmatrix}$ norma Manhattan wynosi:

  $||\vec{v}||_1 = |x| + |y|$

* **Norma maksimum (norma L∞):** Ta norma jest równa największej wartości bezwzględnej spośród współrzędnych wektora. Dla wektora  $\vec{v} = \begin{bmatrix} x \\ y \end{bmatrix}$ norma maksimum wynosi:

  $||\vec{v}||_∞ = \max(|x|, |y|)$

### Przykład z życia codziennego

Wyobraź sobie, że chcesz dostać się z punktu A do punktu B w mieście. Możesz iść różnymi drogami:

* **Najkrótsza droga "na przełaj"** to odpowiednik normy euklidesowej.
* **Droga wzdłuż ulic, tylko na północ/południe i wschód/zachód** to odpowiednik normy Manhattan.
* **Droga, na której najdłuższy odcinek jest jak najkrótszy** to odpowiednik normy maksimum.


In [1]:
import numpy as np

v = np.array([3, 4])

# Norma euklidesowa
norma_euklidesowa = np.linalg.norm(v)  # lub np.linalg.norm(v, 2)
print(f"Norma euklidesowa: {norma_euklidesowa}")

# Norma Manhattan
norma_manhattan = np.linalg.norm(v, 1)
print(f"Norma Manhattan: {norma_manhattan}")

# Norma maksimum
norma_maksimum = np.linalg.norm(v, np.inf)
print(f"Norma maksimum: {norma_maksimum}")

Norma euklidesowa: 5.0
Norma Manhattan: 7.0
Norma maksimum: 4.0


In [ ]:
### Zadania w Python i NumPy

# 1. Utwórz wektor `a` o współrzędnych (-2, 5).
# 2. Oblicz normę euklidesową wektora `a`.
# 3. Oblicz normę Manhattan wektora `a`.
# 4. Oblicz normę maksimum wektora `a`.
# 5. **(Zadanie trudniejsze)** Napisz funkcję, która oblicza normę p-tą wektora (dla dowolnego p >= 1). Norma p-ta wektora  $\vec{v} = \begin{bmatrix} x \\ y \end{bmatrix}$  to  $(\sqrt[p]{|x|^p + |y|^p})$.

In [2]:
### Odpowiedzi do zadań

import numpy as np

# 1. Tworzenie wektora
a = np.array([-2, 5])

# 2. Norma euklidesowa
norma_euklidesowa = np.linalg.norm(a)
print(f"Norma euklidesowa: {norma_euklidesowa}")

# 3. Norma Manhattan
norma_manhattan = np.linalg.norm(a, 1)
print(f"Norma Manhattan: {norma_manhattan}")

# 4. Norma maksimum
norma_maksimum = np.linalg.norm(a, np.inf)
print(f"Norma maksimum: {norma_maksimum}")


# 5. Funkcja obliczająca normę p-tą
def norma_p(wektor, p):
    """Oblicza normę p-tą wektora."""
    return np.power(np.sum(np.abs(wektor) ** p), 1 / p)


print(f"Norma 3-cia wektora a: {norma_p(a, 3)}")


Norma euklidesowa: 5.385164807134504
Norma Manhattan: 7.0
Norma maksimum: 5.0
Norma 3-cia wektora a: 5.104468722001463


## Norma w przestrzeni Rⁿ

W przestrzeni Rⁿ, czyli przestrzeni o n wymiarach, wektory mają n współrzędnych.  Możemy je zapisać jako:

  $\vec{v} = \begin{bmatrix} v_1 \\ v_2 \\ ... \\ v_n \end{bmatrix}$

### Rodzaje norm w Rⁿ

Wzory na normy, które poznaliśmy wcześniej, można łatwo uogólnić na przestrzeń Rⁿ:

* **Norma euklidesowa (norma L2):**

  $||\vec{v}||_2 = \sqrt{v_1^2 + v_2^2 + ... + v_n^2}$

* **Norma Manhattan (norma L1):**

  $||\vec{v}||_1 = |v_1| + |v_2| + ... + |v_n|$

* **Norma maksimum (norma L∞):**

  $||\vec{v}||_∞ = \max(|v_1|, |v_2|, ..., |v_n|)$

* **Norma p-ta:**

  $||\vec{v}||_p = (\sqrt[p]{|v_1|^p + |v_2|^p + ... + |v_n|^p})$

## Odległość dwóch punktów na płaszczyźnie

Odległość między dwoma punktami na płaszczyźnie możemy obliczyć, wykorzystując **twierdzenie Pitagorasa**. 

### Twierdzenie Pitagorasa

W trójkącie prostokątnym kwadrat długości przeciwprostokątnej jest równy sumie kwadratów długości przyprostokątnych: $a^2 + b^2 = c^2$

### Obliczanie odległości

Aby obliczyć odległość między punktami  $A(x_1, y_1)$ i $B(x_2, y_2)$, wykonaj następujące kroki:

1. **Utwórz wektor** łączący te punkty: $\vec{AB} = (x_2 - x_1, y_2 - y_1)$.
2. **Oblicz długość tego wektora**, czyli jego normę euklidesową:

   $||\vec{AB}|| = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$

Ta długość jest właśnie odległością między punktami A i B.

### Przykład

Obliczmy odległość między punktami A(-1, 2) i B(3, 4):

1. Wektor $\vec{AB} = (3 - (-1), 4 - 2) = (4, 2)$
2. Odległość: $||\vec{AB}|| = \sqrt{4^2 + 2^2} = \sqrt{20} = 2\sqrt{5}$

In [3]:
import numpy as np

# Definiujemy punkty
A = np.array([-1, 2])
B = np.array([3, 4])

# Obliczamy odległość
odleglosc = np.linalg.norm(B - A)

# Wyświetlamy wynik
print(f"Odległość między punktami {A} i {B} wynosi: {odleglosc}")

Odległość między punktami [-1  2] i [3 4] wynosi: 4.47213595499958


In [ ]:
### Zadania w Python i NumPy

# 1. Napisz funkcję `odleglosc(A, B)`, która oblicza odległość między dwoma punktami `A` i `B` na płaszczyźnie.
# 2. Utwórz trzy punkty: `P1`=(1, 1), `P2`=(4, 5) i `P3`=(0, 3).
# 3. Oblicz odległości między wszystkimi parami punktów (`P1` i `P2`, `P1` i `P3`, `P2` i `P3`).
# 4. **(Zadanie trudniejsze)**  Napisz funkcję, która sprawdza, czy trzy punkty tworzą trójkąt prostokątny.

In [4]:
### Odpowiedzi do zadań

import numpy as np


# 1. Funkcja obliczająca odległość
def odleglosc(A, B):
    """Oblicza odległość między dwoma punktami A i B."""
    return np.linalg.norm(B - A)


# 2. Tworzenie punktów
P1 = np.array([1, 1])
P2 = np.array([4, 5])
P3 = np.array([0, 3])

# 3. Obliczanie odległości
odl_P1_P2 = odleglosc(P1, P2)
odl_P1_P3 = odleglosc(P1, P3)
odl_P2_P3 = odleglosc(P2, P3)

print(f"Odległość między P1 i P2: {odl_P1_P2}")
print(f"Odległość między P1 i P3: {odl_P1_P3}")
print(f"Odległość między P2 i P3: {odl_P2_P3}")


# 4. Funkcja sprawdzająca trójkąt prostokątny
def czy_trojkat_prostokatny(A, B, C):
    """Sprawdza, czy trzy punkty tworzą trójkąt prostokątny."""
    a = odleglosc(B, C)
    b = odleglosc(A, C)
    c = odleglosc(A, B)
    boki = sorted([a, b, c])  # Sortujemy boki
    return np.isclose(
        boki[0] ** 2 + boki[1] ** 2, boki[2] ** 2
    )  # Twierdzenie Pitagorasa


print(
    f"Czy P1, P2, P3 tworzą trójkąt prostokątny? {czy_trojkat_prostokatny(P1, P2, P3)}"
)

Odległość między P1 i P2: 5.0
Odległość między P1 i P3: 2.23606797749979
Odległość między P2 i P3: 4.47213595499958
Czy P1, P2, P3 tworzą trójkąt prostokątny? True


### Notatka do powtórki

* **Odległość między punktami:** Obliczamy ją jako normę euklidesową wektora łączącego te punkty.
* **Twierdzenie Pitagorasa:** Podstawowe narzędzie do obliczania odległości na płaszczyźnie.
* **NumPy:** `np.linalg.norm(B - A)` oblicza odległość między punktami `A` i `B`.

### Podsumowanie

Umiejętność obliczania odległości między punktami jest kluczowa w geometrii analitycznej i ma wiele zastosowań w praktyce, np. w nawigacji, grafice komputerowej czy analizie danych.

## Macierz

* Macierz to prostokątny układ liczb, symboli lub wyrażeń, ułożonych w wiersze i kolumny.
* Elementy macierzy nazywamy wyrazami.
* Rozmiar macierzy określa liczba wierszy i kolumn (np. macierz 3x2 ma 3 wiersze i 2 kolumny).


## Mnożenie macierzy

Mnożenie macierzy to operacja, która łączy dwie macierze, aby utworzyć trzecią.  **Ważne**: aby móc pomnożyć dwie macierze, `liczba kolumn pierwszej macierzy musi być równa liczbie wierszy drugiej macierzy`.

### Jak mnożymy macierze?

Wynik mnożenia macierzy  $A$ i $B$  oznaczamy jako  $AB$. Element w  $i$-tym wierszu i  $j$-tej kolumnie macierzy  $AB$  obliczamy, mnożąc elementy  $i$-tego wiersza macierzy  $A$  przez odpowiadające im elementy  $j$-tej kolumny macierzy  $B$  i sumując te iloczyny.

**Przykład:**

Załóżmy, że mamy macierze:

$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$  i  $B = \begin{bmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{bmatrix}$

Aby obliczyć element w pierwszym wierszu i pierwszej kolumnie macierzy  $AB$, mnożymy elementy pierwszego wiersza macierzy  $A$  przez elementy pierwszej kolumny macierzy  $B$  i sumujemy:

$(1 * 7) + (2 * 9) + (3 * 11) = 7 + 18 + 33 = 58$

### Własności mnożenia macierzy

* **Mnożenie macierzy nie jest przemienne:**  Zazwyczaj  $AB ≠ BA$.  (Zobacz przykład w kodzie).
* **Mnożenie macierzy jest łączne:**  $(AB)C = A(BC)$
* **Mnożenie macierzy jest rozdzielne względem dodawania:**  $A(B + C) = AB + AC$

* Jeżeli macierz A ma wymiar m x n (m wierszy i n kolumn), a macierz B ma wymiar n x p (n wierszy i p kolumn), to ich iloczyn AB będzie miał wymiar m x p (m wierszy i p kolumn).

In [7]:
import numpy as np

# Definiujemy macierze
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# Mnożenie macierzy
AB = np.dot(A, B)  # lub A @ B
print(f"Macierz AB:\n {AB}")

BA = np.dot(B, A)
print(f"\nMacierz BA:\n {BA}")

A Shape (2, 3)
B Shape (3, 2)
Macierz AB:
 [[ 58  64]
 [139 154]]

Macierz BA:
 [[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


In [ ]:
### Zadania w Python i NumPy

# 1. Utwórz macierz  $C = \begin{bmatrix} 2 & -1 \\ 0 & 3 \end{bmatrix}$  i macierz  $D = \begin{bmatrix} 1 & 4 \\ -2 & 1 \end{bmatrix}$.
# 2. Oblicz iloczyn macierzy  $CD$  i  $DC$.
# 3. Sprawdź, czy mnożenie macierzy  $C$ i $D$  jest przemienne.
# 4. **(Zadanie trudniejsze)** Napisz funkcję, która oblicza  $n$-tą potęgę macierzy kwadratowej (czyli macierz pomnożoną przez siebie  $n$  razy).

In [ ]:
### Odpowiedzi do zadań

import numpy as np

# 1. Tworzenie macierzy
C = np.array([[2, -1], [0, 3]])
D = np.array([[1, 4], [-2, 1]])

# 2. Obliczanie iloczynów
CD = np.dot(C, D)
DC = np.dot(D, C)

print(f"Macierz CD:\n {CD}")
print(f"\nMacierz DC:\n {DC}")

# 3. Sprawdzanie przemienności
czy_przemienne = np.array_equal(CD, DC)
print(f"\nCzy mnożenie C i D jest przemienne? {czy_przemienne}")


# 4. Funkcja obliczająca n-tą potęgę macierzy
def potega_macierzy(macierz, n):
    """Oblicza n-tą potęgę macierzy kwadratowej."""
    wynik = macierz.copy()
    for _ in range(n - 1):
        wynik = np.dot(wynik, macierz)
    return wynik


E = np.array([[1, 2], [3, 4]])
print(f"\nMacierz E do potęgi 3:\n {potega_macierzy(E, 3)}")

### Notatka do powtórki

* **Mnożenie macierzy:**  Operacja łącząca dwie macierze.
* **Warunek mnożenia:** Liczba kolumn pierwszej macierzy musi być równa liczbie wierszy drugiej.
* **Własności:** Nieprzemienne, łączne, rozdzielne względem dodawania.
* **NumPy:** `np.dot(A, B)` lub `A @ B` oblicza iloczyn macierzy `A` i `B`.

### Podsumowanie

Mnożenie macierzy to ważna operacja w algebrze liniowej, która ma szerokie zastosowanie w wielu dziedzinach, takich jak grafika komputerowa, uczenie maszynowe czy fizyka.