# Pandas

In [24]:
import pandas as pd
import numpy as np

pd.__version__

'2.2.3'

Pandas opiera się na dwóch głównych strukturach:

* **Series:** Jednowymiarowa tablica z etykietami. Można ją traktować jako kolumnę w arkuszu kalkulacyjnym.
* **DataFrame:** Dwuwymiarowa tablica z etykietami wierszy i kolumn. Przypomina tabelę w bazie danych lub arkusz kalkulacyjny.



In [22]:
# Tworzenie obiektu Series
s = pd.Series(data=[3, 2, 4, 6, 5])
s_index = pd.Series(
    data=[3, 2, 4, 6, 5], index=["a", "b", "c", "d", "e"], name="sample"
)
s
s_index

# Do elementów Series możemy odwoływać się za pomocą indeksów:
print(s_index["c"])  # Wynik: 5

4


## Uzupełnienie braków w danych


In [14]:
s = pd.Series(
    data=[3, 2, np.nan, 6, 5], index=["a", "b", "c", "d", "e"], name="sample"
)  # np.nan - pusty obiekt, wartość NaN
s

a    3.0
b    2.0
c    NaN
d    6.0
e    5.0
Name: sample, dtype: float64

## Wartoś NaN 

- `NaN` (Not a Number) to specjalna wartość zmiennoprzecinkowa w NumPy, która reprezentuje niezdefiniowany lub niereprezentowalny wynik. Na przykład, 0/0 lub pierwiastek kwadratowy z liczby ujemnej.

- `NaN` jest często używany do reprezentowania brakujących danych w zbiorach danych.

### Funkcje do obsługi NaN
- `np.nan_to_num(x)`: Zastępuje NaN wartością 0.
- `np.nanmean()`: Oblicza średnią, ignorując NaN.

In [32]:
import numpy as np

# Użyj np.nan
x = np.nan

# Użyj np.array() z dtype=float
y = np.array([1, 2, np.nan], dtype=float)

# Użyj np.isnan()
np.isnan(x)  # True


# Utwórz macierz z NaN
macierz = np.array([[1, 2, np.nan], [4, np.nan, 6], [np.nan, 8, 9]])

# Sprawdź, które elementy są NaN
nan_indeksy = np.isnan(macierz)
print(nan_indeksy)
# [[False False  True]
#  [False  True False]
#  [ True False False]]

# Zastąp NaN wartością 0
macierz_bez_nan = np.nan_to_num(macierz)
print(macierz_bez_nan)
# [[1. 2. 0.]
#  [4. 0. 6.]
#  [0. 8. 9.]]

[[False False  True]
 [False  True False]
 [ True False False]]
[[1. 2. 0.]
 [4. 0. 6.]
 [0. 8. 9.]]


In [30]:
# Tworzenie obiektu Series z Data jako indeks

data_indeks = pd.Series(
    data=np.arange(10), index=pd.date_range("2024-10-14", periods=10)
)

data_indeks

2024-10-14    0
2024-10-15    1
2024-10-16    2
2024-10-17    3
2024-10-18    4
2024-10-19    5
2024-10-20    6
2024-10-21    7
2024-10-22    8
2024-10-23    9
Freq: D, dtype: int64

In [38]:
# Tworzenie obiektu series zawierającego dane tekstowe

s_text = pd.Series(data=["python", "java", "sql"], name="language")


print(s_text)
print(s_index.index)
print(s_index.values)

0    python
1      java
2       sql
Name: language, dtype: object
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[3 2 4 6 5]


In [53]:
price = pd.Series(data={"apple": 200, "CD Projekt": 60, "Google": 400, "amazon": 400})
price

print(price["apple"])
# print(price[0])

# Zlicz elementy
print(price.count())

# Zlicza ile razy występuje ta sama wartosc

price.value_counts()

print(price.describe())

200
4
count      4.000000
mean     265.000000
std      166.032125
min       60.000000
25%      165.000000
50%      300.000000
75%      400.000000
max      400.000000
dtype: float64


Oto najważniejsze atrybuty obiektu `Series` w bibliotece pandas:

* **`values`**: Zwraca tablicę NumPy zawierającą wartości `Series`.
* **`index`**: Zwraca etykiety indeksu `Series`.
* **`dtype`**: Zwraca typ danych elementów `Series`.
* **`size`**: Zwraca liczbę elementów `Series`.
* **`name`**: Zwraca nazwę `Series` (jeśli jest ustawiona).
* **`shape`**: Zwraca kształt `Series` (w tym przypadku zawsze będzie to (n,), gdzie n to liczba elementów).
* **`nbytes`**: Zwraca rozmiar `Series` w bajtach.
* **`ndim`**: Zwraca liczbę wymiarów `Series` (w tym przypadku zawsze będzie to 1).

Te atrybuty dostarczają podstawowych informacji o obiekcie `Series` i są często używane do eksploracji i analizy danych.

## Najważniejsze metody Data Series

Obiekty `Data Series` w bibliotece pandas oferują wiele metod do manipulacji i analizy danych. Oto niektóre z najważniejszych:

*   `.head()`: Zwraca pierwsze n wierszy `Series` (domyślnie 5).
*   `.tail()`: Zwraca ostatnie n wierszy `Series` (domyślnie 5).
*   `.describe()`: Zwraca podstawowe statystyki opisowe `Series`, takie jak średnia, odchylenie standardowe, minimum, maksimum itp.
*   `.value_counts()`: Zwraca liczbę wystąpień każdej unikalnej wartości w `Series`.
*   `.sort_values()`: Sortuje `Series` według wartości.
*   `.sort_index()`: Sortuje `Series` według indeksu.
*   `.fillna()`: Wypełnia brakujące wartości w `Series`.
*   `.dropna()`: Usuwa brakujące wartości z `Series`.
*   `.apply()`: Stosuje funkcję do każdego elementu `Series`.
*   `.map()`: Ma zastosowanie do każdego elementu `Series` funkcji lub słownika mapującego.
*   `.astype()`: Konwertuje typ danych `Series`.
*   `.isin()`: Sprawdza, czy elementy `Series` znajdują się w podanej liście wartości.
*   `.between()`: Sprawdza, czy elementy `Series` znajdują się w podanym przedziale.
*   `.unique()`: Zwraca unikalne wartości `Series`.
*   `.nunique()`: Zwraca liczbę unikalnych wartości `Series`.
*   `.idxmax()`: Zwraca indeks elementu o maksymalnej wartości.
*   `.idxmin()`: Zwraca indeks elementu o minimalnej wartości.
*   `.sum()`: Zwraca sumę elementów `Series`.
*   `.mean()`: Zwraca średnią arytmetyczną elementów `Series`.
*   `.median()`: Zwraca medianę elementów `Series`.
*   `.std()`: Zwraca odchylenie standardowe elementów `Series`.
*   `.var()`: Zwraca wariancję elementów `Series`.
*   `.quantile()`: Zwraca kwantyl o podanym poziomie.
*   `.count()`: Zwraca liczbę niepustych elementów `Series`.
*   `.to_csv()`: Zapisuje `Series` do pliku CSV.
*   `.to_excel()`: Zapisuje `Series` do pliku Excel.

## Przykład

```python
import pandas as pd

# Utwórz Series
s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])

# Wyświetl pierwsze 3 elementy
print(s.head(3))

# Wyświetl podstawowe statystyki
print(s.describe())

# Zastosuj funkcję lambda do każdego elementu
print(s.apply(lambda x: x * 2))
```

## W obiekcie DataSeries index może się powtarzać !


Metoda `squeeze()` służy do konwersji DataFrame z jedną kolumną do Series. Jest to bardziej "pandasowy" sposób na osiągnięcie tego samego rezultatu. 

```python
import pandas as pd

# Wczytaj dane z pliku CSV
s = pd.read_csv('dane.csv', header=None, index_col=0).squeeze()

# Wyświetl Series
print(s)
```

Metody i właściwości Data Series do pobierania wartości
Pandas Series oferuje różnorodne metody i właściwości, które pozwalają na pobieranie wartości. Oto omówienie niektórych z nich:

Metody
- iloc[]: Pobieranie wartości za pomocą indeksów liczbowych.
- loc[]: Pobieranie wartości za pomocą etykiet.
- at[]: Pobieranie pojedynczej wartości za pomocą etykiety.
- iat[]: Pobieranie pojedynczej wartości za pomocą indeksu liczbowego.
- get(): Pobieranie wartości za pomocą etykiety z domyślną wartością, jeśli etykieta nie istnieje.

Właściwości
- .values: Pobiera wszystkie wartości serii jako tablicę NumPy.
- .index: Pobiera indeksy serii.
- .size: Pobiera rozmiar serii.
- .empty: Sprawdza, czy seria jest pusta.

## Różnice między metodami i właściwościami w Data Series

### iloc[] vs. loc[]: (preferowane)

- iloc[]: Używa liczbowych indeksów pozycyjnych. Używany do dostępu przez pozycję indeksu.
- loc[]: Używa etykiet indeksów (kluczy). Używany do dostępu przez nazwane etykiety indeksów.

### at[] vs. iat[]:

- at[]: Służy do pobierania pojedynczej wartości za pomocą etykiety indeksu. Jest szybszy niż loc[] dla pojedynczych elementów.
- iat[]: Służy do pobierania pojedynczej wartości za pomocą liczbowego indeksu pozycyjnego. Jest szybszy niż iloc[] dla pojedynczych elementów.

### get():

- get(): Pobiera wartość na podstawie etykiety indeksu z opcjonalną wartością domyślną, jeśli etykieta nie istnieje. Przydatny, gdy nie jesteśmy pewni, czy etykieta istnieje.

### .values vs. .index vs. .size vs. .empty:

- .values: Zwraca wszystkie wartości serii jako tablicę NumPy.
- .index: Zwraca indeksy serii.
- .size: Zwraca liczbę elementów w serii.
- .empty: Sprawdza, czy seria jest pusta i zwraca True lub False.

## Najlepsze praktyki
Wybór odpowiedniej metody:

- Używaj iloc[], gdy znasz pozycję indeksu, a loc[], gdy pracujesz z etykietami.
- Używaj at[] i iat[], gdy potrzebujesz szybkiego dostępu do pojedynczej wartości.

### Bezpieczne pobieranie wartości:

    Używaj get(), gdy nie jesteś pewien, czy dana etykieta istnieje. Dzięki temu unikniesz błędów KeyError.

```python
import pandas as pd

# Przykładowe dane
series = pd.Series([1, 2, 3], index=['a', 'b', 'c'])

# Użycie metody get() z wartością domyślną
value = series.get('d', default='Wartość domyślna')

print(value)  # Powinno zwrócić 'Wartość domyślna'

```

- Manipulacja wartościami:

    Używaj .values do przekształcania serii na tablicę NumPy, gdy planujesz przeprowadzać operacje numeryczne na dużych zbiorach danych.

- Sprawdzanie właściwości serii:

    Regularnie korzystaj z .index, .size i .empty, aby zrozumieć strukturę i stan swojej serii.

- Unikanie błędów:

    Sprawdź, czy indeksy lub etykiety istnieją przed dostępem do wartości, aby uniknąć wyjątków IndexError i KeyError.

## Przykład użycia loc i reindex w pandas, gdy jeden z szukanych indeksów nie istnieje

Gdy próbujesz uzyskać wartości za pomocą loc, a szukany indeks nie istnieje, pandas zgłosi błąd KeyError.

```python
import pandas as pd

# Przykładowe dane
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data, index=['x', 'y', 'z'])

# Próbuj uzyskać wartości dla istniejących i nieistniejących indeksów za pomocą loc
try:
    result_loc = df.loc[['x', 'y', 'w']]
except KeyError as e:
    print("KeyError:", e)

```

W powyższym przykładzie loc zgłosi KeyError, ponieważ indeks 'w' nie istnieje w DataFrame.

- Użycie reindex
Gdy używasz reindex i jeden z nowych indeksów nie istnieje w oryginalnym obiekcie, pandas doda ten indeks z wartością NaN.

```python
import pandas as pd

# Przykładowe dane
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data, index=['x', 'y', 'z'])

# Reindeksowanie z brakującymi indeksami
new_index = ['x', 'y', 'w']
df_reindexed = df.reindex(new_index)

print(df_reindexed)

```
Wynik:

```text
     A    B
x  1.0  4.0
y  2.0  5.0
w  NaN  NaN

```

W powyższym przykładzie reindex dodał nowy indeks 'w' z wartościami NaN, ponieważ ten indeks nie istniał w oryginalnym DataFrame.

Podsumowanie
`loc`: Podnosi KeyError, gdy próbujesz uzyskać wartości dla nieistniejących indeksów. `reindex`: Dodaje brakujące indeksy z wartościami NaN.

In [ ]:
# Intersection

# Wyszuka tylko dane występujące razem w obu zboiorach i pominie te których brak bez wyświetlenia błędu

# Idxmin, Idxmax - numery indeksów na których występują minimnalne i maksymalne wartosci


## Metoda map

Metoda `map` w Pandas Series pozwala na mapowanie wartości z jednej serii na wartości z innej serii. W tym przypadku, seria A dostarcza indeks, a seria B dostarcza wartości. 

**Przykład:**

```python
import pandas as pd

# Seria A (indeks)
seria_a = pd.Series(['jabłko', 'banan', 'gruszka'], index=[1, 2, 3])

# Seria B (wartości)
seria_b = pd.Series([10, 20, 30], index=['jabłko', 'banan', 'gruszka'])

# Połączenie serii A i B za pomocą metody map
wynik = seria_a.map(seria_b)

# Wyświetlenie wyniku
print(wynik)
```

**Wynik:**

```
1    10
2    20
3    30
dtype: int64
```

W tym przykładzie, `seria_a` zawiera indeksy (1, 2, 3) i odpowiadające im etykiety ('jabłko', 'banan', 'gruszka'). `seria_b` zawiera etykiety jako indeks i wartości (10, 20, 30). Metoda `map` zastosowana do `seria_a` z argumentem `seria_b` tworzy nową serię, w której indeksem są indeksy z `seria_a`, a wartościami są wartości z `seria_b` odpowiadające etykietom z `seria_a`.

Metoda `map` jest bardzo przydatna do łączenia danych z różnych źródeł, gdy mamy wspólną kolumnę lub indeks.

## DataFrame 

DataFrame to dwuwymiarowa struktura danych,  która przypomina tabelę w bazie danych lub arkusz kalkulacyjny. Składa się z wierszy i kolumn, gdzie każda kolumna może mieć inny typ danych (liczby, tekst, daty itp.). DataFrame posiada etykiety wierszy (indeks) i etykiety kolumn.

### Tworzenie DataFrame
DataFrame można utworzyć na wiele sposobów, np. z:

- słownika list lub tablic
- listy słowników
- pliku CSV
- tabeli bazy danych

In [56]:
df = pd.DataFrame(
    data={"Cena": [10, 20, 30], "Ilość": [2, 3, 4]}, index=["a", "b", "c"]
)
df

# Utwórz DataFrame ze słownika list
df = pd.DataFrame(
    {
        "Imię": ["Jan", "Anna", "Piotr", "Maria"],
        "Wiek": [25, 30, 28, 22],
        "Miasto": ["Warszawa", "Kraków", "Poznań", "Gdańsk"],
    }
)

df

Imię  Wiek    Miasto
0    Jan    25  Warszawa
1   Anna    30    Kraków
2  Piotr    28    Poznań
3  Maria    22    Gdańsk

### Dostęp do Danych

Do danych w DataFrame można odwoływać się na wiele sposobów:

*   za pomocą etykiet kolumn (`df['Imię']`)
*   za pomocą atrybutów (`df.Imię`)
*   za pomocą indeksowania (`df.iloc[0, 1]`)
*   za pomocą indeksowania logicznego (`df[df['Wiek'] > 25]`)

### Atrybuty i Metody

DataFrame posiada wiele atrybutów i metod, które ułatwiają pracę z danymi:

*   `shape`: Zwraca wymiary DataFrame (liczba wierszy, liczba kolumn).
*   `columns`: Zwraca etykiety kolumn.
*   `index`: Zwraca etykiety wierszy.
*   `head()`: Wyświetla pierwsze n wierszy.
*   `tail()`: Wyświetla ostatnie n wierszy.
*   `describe()`: Wyświetla podstawowe statystyki opisowe.
*   `info()`: Wyświetla informacje o DataFrame (typy danych, brakujące wartości).
*   `sort_values()`: Sortuje DataFrame według wartości w kolumnie.
*   `groupby()`: Grupuje dane według wartości w kolumnie.

### Ściąga na Egzamin

*   **DataFrame:** Dwuwymiarowa tabela z etykietami wierszy i kolumn.
*   **Tworzenie:** `pd.DataFrame(dane)`
*   **Dostęp do danych:** `df['kolumna']`, `df.kolumna`, `df.iloc[]`, `df.loc[]`
*   **Atrybuty:** `shape`, `columns`, `index`
*   **Metody:** `head()`, `tail()`, `describe()`, `info()`, `sort_values()`, `groupby()`


In [ ]:
### Zadania

# 1. Utwórz DataFrame z danymi o studentach (imię, nazwisko, wiek, kierunek).
# 2. Wyświetl tylko dane studentów, którzy mają więcej niż 22 lata.
# 3. Posortuj DataFrame według wieku studentów.

In [ ]:
### Odpowiedzi do Zadań


import pandas as pd

# Zadanie 1
dane_studentow = {
    "Imię": ["Jan", "Anna", "Piotr", "Maria"],
    "Nazwisko": ["Kowalski", "Nowak", "Wiśniewski", "Kamińska"],
    "Wiek": [25, 30, 28, 22],
    "Kierunek": ["Informatyka", "Matematyka", "Fizyka", "Biologia"],
}
df_studenci = pd.DataFrame(dane_studentow)

# Zadanie 2
starsi_studenci = df_studenci[df_studenci["Wiek"] > 22]
print("Starsi studenci:\n", starsi_studenci, "\n")

# Zadanie 3
posortowani_studenci = df_studenci.sort_values("Wiek")
print("Posortowani studenci:\n", posortowani_studenci)

## Funkcja apply()

Funkcja `apply()` w bibliotece pandas służy do stosowania funkcji do każdego wiersza lub kolumny DataFrame'u. Jest to bardzo elastyczne narzędzie, które pozwala na wykonywanie różnego rodzaju operacji na danych.

### Składnia

```python
df.apply(func, axis=0, raw=False, result_type=None, args=(), **kwargs)
```

* `func`: Funkcja do zastosowania.
* `axis`: Oś, wzdłuż której ma być zastosowana funkcja (0 dla kolumn, 1 dla wierszy).
* `raw`: Jeśli True, przekazuje funkcjom tablice NumPy zamiast obiektów Series.
* `result_type`: Określa typ zwracanego obiektu ('expand', 'reduce', 'broadcast').
* `args`: Dodatkowe argumenty pozycyjne dla funkcji.
* `kwargs`: Dodatkowe argumenty nazwane dla funkcji.

### Przykłady

```python
import pandas as pd

# Utwórz DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})

# Zastosuj funkcję lambda do każdej kolumny
df_apply_kolumny = df.apply(lambda x: x * 2, axis=0)
print(df_apply_kolumny)
#     A   B   C
# 0  2   8  14
# 1  4  10  16
# 2  6  12  18

# Zastosuj funkcję lambda do każdego wiersza
df_apply_wiersze = df.apply(lambda x: x * 2, axis=1)
print(df_apply_wiersze)
#     A   B   C
# 0  2   8  14
# 1  4  10  16
# 2  6  12  18

# Zastosuj funkcję zdefiniowaną przez użytkownika do każdej kolumny
def dodaj_10(x):
  return x + 10

df_apply_dodaj_10 = df.apply(dodaj_10, axis=0)
print(df_apply_dodaj_10)
#     A   B   C
# 0  11  14  17
# 1  12  15  18
# 2  13  16  19
```

### Ściąga

* `apply()` stosuje funkcję do wierszy lub kolumn DataFrame'u.
* `axis=0`: kolumny, `axis=1`: wiersze.
* Można używać funkcji lambda i funkcji zdefiniowanych przez użytkownika.



In [ ]:
### Zadania

# 1. Utwórz DataFrame z kolumnami 'Cena' i 'Ilość'.
# 2. Użyj `apply()` do obliczenia wartości kolumny 'Wartość' jako iloczyn 'Cena' * 'Ilość'.
# 3. **(Zadanie trudniejsze)** Napisz funkcję, która normalizuje wartości w kolumnie do przedziału 0-1 i zastosuj ją do DataFrame'u.

In [ ]:
### Odpowiedzi do Zadań

import pandas as pd

# Zadanie 1
df = pd.DataFrame({"Cena": [10, 20, 30], "Ilość": [2, 3, 4]})

# Zadanie 2
df["Wartość"] = df.apply(lambda row: row["Cena"] * row["Ilość"], axis=1)
print(df, "\n")


# Zadanie 3 (trudniejsze)
def normalizuj(x):
    """Normalizuje wartości w Series do przedziału 0-1."""
    min_val = x.min()
    max_val = x.max()
    return (x - min_val) / (max_val - min_val)


df_norm = df.apply(normalizuj, axis=0)
print(df_norm)

## Dostęp do danych

```python
import pandas as pd

# Utwórz DataFrame
df = pd.DataFrame({'Imię': ['Jan', 'Anna', 'Piotr', 'Maria'],
                   'Wiek': [25, 30, 28, 22],
                   'Miasto': ['Warszawa', 'Kraków', 'Poznań', 'Gdańsk']})

# Wyświetl DataFrame
print("DataFrame:\n", df, "\n")

# Wybierz kolumnę "Wiek"
kolumna_wiek = df["Wiek"]

# Wybierz pierwszy wiersz
wiersz_0 = df.iloc[0]

# Wybierz element z drugiego wiersza i trzeciej kolumny
element_1_2 = df.iloc[1, 2]

# Wybierz wszystkie wiersze, w których wiek jest większy niż 25
df_wiek_25 = df[df['Wiek'] > 25]

# Wybierz kolumny 'Imię' i 'Miasto' dla pierwszych dwóch wierszy
df_imie_miasto = df.loc[:1, ['Imię', 'Miasto']]

# Wyświetl wyniki
print("Kolumna 'Wiek':\n", kolumna_wiek, "\n")
print("Pierwszy wiersz:\n", wiersz_0, "\n")
print("Element z drugiego wiersza i trzeciej kolumny:", element_1_2, "\n")
print("Wiersze, w których wiek jest większy niż 25:\n", df_wiek_25, "\n")
print("Kolumny 'Imię' i 'Miasto' dla pierwszych dwóch wierszy:\n", df_imie_miasto, "\n")

# Wyświetl typy
print("Typ kolumna_wiek:", type(kolumna_wiek))
print("Typ wiersz_0:", type(wiersz_0))
print("Typ element_1_2:", type(element_1_2))
print("Typ df_wiek_25:", type(df_wiek_25))
print("Typ df_imie_miasto:", type(df_imie_miasto))
```

```text

DataFrame:
     Imię  Wiek    Miasto
0    Jan    25  Warszawa
1   Anna    30    Kraków
2  Piotr    28    Poznań
3  Maria    22    Gdańsk 

Kolumna 'Wiek':
 0    25
1    30
2    28
3    22
Name: Wiek, dtype: int64 

Pierwszy wiersz:
Imię           Jan
Wiek            25
Miasto    Warszawa
Name: 0, dtype: object 

Element z drugiego wiersza i trzeciej kolumny: Kraków 

Wiersze, w których wiek jest większy niż 25:
     Imię  Wiek  Miasto
1   Anna    30  Kraków
2  Piotr    28  Poznań 

Kolumny 'Imię' i 'Miasto' dla pierwszych dwóch wierszy:
    Imię    Miasto
0   Jan  Warszawa
1  Anna    Kraków 

Typ kolumna_wiek: <class 'pandas.core.series.Series'>
Typ wiersz_0: <class 'pandas.core.series.Series'>
Typ element_1_2: <class 'str'>
Typ df_wiek_25: <class 'pandas.core.frame.DataFrame'>
Typ df_imie_miasto: <class 'pandas.core.frame.DataFrame'>

```

W DataFrame można uzyskać dostęp do danych i wycinać ich fragmenty na wiele sposobów:

**Wybieranie kolumn:**

*   Za pomocą nazwy kolumny: `df['nazwa_kolumny']`
*   Za pomocą atrybutu: `df.nazwa_kolumny` (jeśli nazwa kolumny jest prawidłowym identyfikatorem Pythona)

**Wybieranie wierszy:**

*   Za pomocą `iloc`: `df.iloc[indeks_wiersza]` - wybiera wiersz o podanym indeksie liczbowym
*   Za pomocą `loc`: `df.loc[etykieta_wiersza]` - wybiera wiersz o podanej etykiecie

**Wybieranie pojedynczych elementów:**

*   Za pomocą `iloc`: `df.iloc[indeks_wiersza, indeks_kolumny]`

**Wybieranie fragmentów DataFrame:**

*   Za pomocą indeksowania logicznego: `df[warunek]` - wybiera wiersze spełniające warunek
*   Za pomocą `loc`: `df.loc[etykiety_wierszy, etykiety_kolumn]` - wybiera wiersze i kolumny o podanych etykietach
*   Za pomocą `iloc`: `df.iloc[indeksy_wierszy, indeksy_kolumn]` - wybiera wiersze i kolumny o podanych indeksach liczbowych

**Typy zwracanych obiektów:**

*   Wybieranie pojedynczej kolumny zwraca obiekt `Series`.
*   Wybieranie pojedynczego wiersza zwraca obiekt `Series`.
*   Wybieranie pojedynczego elementu zwraca wartość elementu (np. liczbę, ciąg znaków).
*   Wybieranie fragmentu DataFrame zwraca obiekt `DataFrame`.

Pamiętaj, że indeksowanie w Pythonie zaczyna się od 0.
