In [3]:
import numpy as np

## Tablice 1D

In [4]:
# Spróbuj stworzyć kilka tablic NumPy o różnych kształtach i użyj funkcji `size`, aby sprawdzić, ile elementów zawiera każda z nich.

tablica = np.array([[1, 2, 3], [4, 5, 6]])
print(tablica.size)

6


In [5]:
# Tworzenie tablicy z podaniem typu danych

arr = np.array([1, 2, 3, 4, 5], dtype="float")
print(arr.dtype)
arr

float64


array([1., 2., 3., 4., 5.])

In [6]:
# Spróbuj stworzyć kilka tablic NumPy o różnych kształtach i użyj funkcji `shape`, aby sprawdzić ich wymiary.
# Następnie spróbuj zmienić kształt jednej z tablic za pomocą atrybutu `shape`.

# Tworzenie przykładowej tablicy 1D
arr = np.array([1, 2, 3, 4, 5, 6])

# Zmiana kształtu na 2x3 bez tworzenia nowej tablicy
arr.shape = (2, 3)

print(arr)  # [[1 2 3] [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [4]:
# Spróbuj stworzyć kilka tablic NumPy z różnymi typami danych i użyj atrybutu `dtype`, aby sprawdzić, jaki typ danych przechowuje każda z nich.
# Następnie spróbuj zmienić typ danych jednej z tablic za pomocą metody `astype()`.

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

# Zmiana typu
arr = arr.astype(float)
print(arr.dtype)

int64
float64


In [32]:
# Stwórz tablicę NumPy o 10 elementach (liczby od 1 do 10).

arr = np.arange(1, 11)
print(arr)

# Wyciągnij z tablicy pierwszy element oraz ostatni element.
first_element = arr[0]
last_element = arr[-1]

print("Pierwszy element:", first_element)
print("Ostatni element:", last_element)

# Wyciągnij podtablicę zawierającą elementy od 3 do 7 (z indeksami).

subarray = arr[2:7]
print("Podtablica:", subarray)

[ 1  2  3  4  5  6  7  8  9 10]
Pierwszy element: 1
Ostatni element: 10
Podtablica: [3 4 5 6 7]


## Tablica 2D

In [42]:
# Tworzenie tablicy 2D i operacje na wierszach i kolumnach
# Stwórz tablicę 2D o wymiarach 3x3 z liczbami od 1 do 9.

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.size(arr2D))

# Wyciągnij drugi wiersz tej tablicy.

seccond_row = arr2D[1, :]
print("Drugi wiersz", seccond_row)
# Pierwsza liczba 1 oznacza, że chcemy wybrać drugi wiersz tablicy (pamiętaj, że indeksowanie w Pythonie zaczyna się od 0, więc 0 to pierwszy wiersz, 1 to drugi itd.).
# Dwukropek : oznacza, że chcemy wybrać wszystkie elementy z tego wiersza (czyli wszystkie kolumny).


# Wyciągnij drugą kolumnę tej tablicy.
print("Druga kolumna", arr2D[:, 1])

# Zmień element w pierwszym wierszu, pierwszej kolumnie na wartość 99.
# Podpowiedź: Indeksuj tablicę, np. arr[1, :] wyciągnie drugi wiersz, a arr[:, 1] wyciągnie drugą kolumnę.

9
Drugi wiersz [4 5 6]
Druga kolumna [2 5 8]


In [36]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


## Macierze 3D

In [43]:
# Stwórz tablicę 3D o wymiarach 2x3x3 z liczbami od 1 do 18.
# Wyciągnij pierwszą "szafkę" (pierwszy blok o wymiarach 3x3).
# Zmień wartość w drugiej "szafce", drugim wierszu, trzeciej kolumnie na wartość 42.
# Wyciągnij wszystkie elementy z trzeciej kolumny we wszystkich szafkach.
# Podpowiedź: Pamiętaj o indeksowaniu w trzech wymiarach np. arr[1, :, :] dla drugiej "szafki".


import numpy as np

# 1. Tworzenie tablicy 3D
arr_3d = np.arange(1, 19).reshape(2, 3, 3)

# 2. Wyciąganie pierwszej szafki
first_shelf = arr_3d[0, :, :]

# 3. Zmiana elementu w drugiej szafce, drugim wierszu, trzeciej kolumnie
arr_3d[1, 1, 2] = 42

# 4. Wyciąganie wszystkich elementów z trzeciej kolumny we wszystkich szafkach
third_column = arr_3d[:, :, 2]

print("Pierwsza szafka:", first_shelf)
print("Tablica po zmianie:", arr_3d)
print("Trzecia kolumna:", third_column)

Pierwsza szafka: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tablica po zmianie: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 42]
  [16 17 18]]]
Trzecia kolumna: [[ 3  6  9]
 [12 42 18]]


In [15]:
#  Stworzyć tablicę 3x4 wypełnioną losowymi liczbami całkowitymi z zakresu od 1 do 10.

arr_3x4 = np.random.randint(1, 11, size=(3, 4))
arr_3x4


# * Stworzyć tablicę 5x5 wypełnioną wartością logiczną `False`.

arr_5x5 = np.full((5, 5), False)
arr_5x5

# * Stworzyć tablicę jednowymiarową zawierającą 10 liczb równomiernie rozmieszczonych między -5 a 5.

# 5 liczb równomiernie rozmieszczonych od -5 do 5 (włącznie)
tablica_liniowa = np.linspace(-5, 5, 5)
print(tablica_liniowa)

[-5.  -2.5  0.   2.5  5. ]


In [8]:
arr = np.arange(start=0, stop=10, step=0.5)
arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

## Podstawowe operacje na tablicach

In [2]:
import numpy as np

A = np.array([3, 1, 4, 2], dtype=np.float64)
B = np.array([3, -1, 3, 2], dtype="float")

print(A)
print(B)

# Dodawanie, odejmowanie tablic (rozmiar musi się zgadzac)
print("Dodawanie elementów", A + B)
print("Dodawanie elementów metoda", np.add(A, B))
print("Odejmowanie elementów", A - B)
print("Odejmowanie elementów metoda", np.subtract(A, B))
print("Mnożenie elementów", A * B)
print("Mnożenie elementów metoda", np.multiply(A, B))
print("Dzielenie elementów metoda", np.subtract(A, B))

# Dodawanie stałej do kazdego elementu
print("Dodawanie stałej", A + 4)

[3. 1. 4. 2.]
[ 3. -1.  3.  2.]
Dodawanie elementów [6. 0. 7. 4.]
Dodawanie elementów metoda [6. 0. 7. 4.]
Odejmowanie elementów [0. 2. 1. 0.]
Mnożenie elementów [ 9. -1. 12.  4.]
Dzielenie elementów [ 1.         -1.          1.33333333  1.        ]
Dodawanie stałej [7. 5. 8. 6.]


In [3]:
array3 = np.arange(3, 9)
print(array3)

[3 4 5 6 7 8]


In [7]:
A = np.array([[2, 1, 0], [-1, 2, 3], [0, 1, 3]], dtype=float)
print(np.linalg.det(A))


9.000000000000002


In [15]:
import numpy as np

# 5x - 4 = 11

# Definiujemy współczynniki równania
a = np.array([[5]])  # Macierz współczynników
b = np.array([15])  # Wektor wyników (11 + 4)

# Rozwiązujemy równanie
x = np.linalg.solve(a, b)

print(f"Rozwiązanie: x = {x[0]}")

print("sss:", np.linalg.solve([[5]], [[15]]))

# ( 2x + 3 = 7 )

print(f"2x + 3 = 7 x wynosi: {np.linalg.solve([[2]], [[7-3]])} ")

# ( 5x - 4 = 11 )
print(f"5x - 4 = 11 x wynosi: {np.linalg.solve([[5]], [[11+4]])} ")

# ( 3x + 2 = 2x + 5 )
# ( 4x - 7 = 9 )
# ( 6x + 3 = 2x + 15 )
# ( 7x - 5 = 2x + 10 )
# ( 8x + 4 = 4x + 20 )
# ( 9x - 3 = 3x + 15 )
# ( 10x + 2 = 5x + 12 )
# ( 11x - 6 = 5x + 18 )

Rozwiązanie: x = 3.0
sss: [[3.]]
2x + 3 = 7 x wynosi: [[2.]] 
5x - 4 = 11 x wynosi: [[3.]] 


In [16]:
np.exp(1)


np.float64(2.718281828459045)

In [5]:
import numpy as np

A = np.random.rand(5)
print(A)

[0.18048581 0.63260229 0.64625056 0.62434992 0.05933651]


In [10]:
A = np.random.rand(5)
np.argmax(A)
MaxValue = A[np.argmax(A)]
MinValue = A[np.argmin(A)]
ArgSort = np.argsort(A)

print("MaxValue", MaxValue)

MaxValue 0.9751517962174442


In [13]:
print("MaxValue", np.max(A))
print("MinValue", np.min(A))
print("MeanValue", np.mean(A))  # Srednia arytmetyczna
print("MedianValue", np.median(A))

MaxValue 0.9751517962174442
MinValue 0.19711700425894363
MeanValue 0.5414406816692539
MedianValue 0.4330262501058566
